#!/bin/bash

DB_NAME1="lab_local"
DB_NAME2="lab_test"
OUT_FILE_NAME="labbackup"
VERSION="v1.0.4"
OUT_FILE="$OUT_FILE_NAME-$VERSION.tar"

# take the dump
mysqldump $DB_NAME1 > $DB_NAME1
if [ $? -ne 0 ]; then
  echo "Error: Something went wrong while taking db dump."
  echo "Aborting backup."
  exit 1;
fi
mysqldump $DB_NAME2 > $DB_NAME2
if [ $? -ne 0 ]; then
  echo "Error: Something went wrong while taking db dump."
  echo "Aborting backup."
  exit 1;
fi

# tar the $DB_NAME folder
tar cfvz $OUT_FILE $DB_NAME1 $DB_NAME2
if [ $? -ne 0 ]; then
  echo "Error: Something went wrong while tar-ing the dump."
  echo "Aborting backup."
  exit 1;
fi

#clean up data
rm $DB_NAME1 $DB_NAME2
echo "Backup successful."
exit 0;

    Status API Training Shop Blog About 

